# SPDX-FileCopyrightText: © Vegard IT GmbH (https://vegardit.com) and contributors
# SPDX-FileContributor: Sebastian Thomschke, Vegard IT GmbH
# SPDX-License-Identifier: Apache-2.0
#
# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax
name: Test "setup-haxe-targets" Action

on:  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  schedule:
    # https://docs.github.com/en/actions/reference/choosing-when-your-workflow-runs/events-that-trigger-workflows
    - cron: '0 10 1 * *'
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - '**/*.adoc'
    - '**/*.md'
    - '.github/*.yml'
    - '.github/actions/test-with-haxe/*'
    - '.github/workflows/*test-with-haxe*.yml'
  pull_request:
    paths-ignore:
    - '**/*.adoc'
    - '**/*.md'
    - '.github/*.yml'
    - '.github/actions/test-with-haxe/*'
    - '.github/workflows/*test-with-haxe*.yml'
  workflow_dispatch:
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
    inputs:
      debug-with-ssh:
        description: "Start an SSH session for debugging purposes after tests ran:"
        default: never
        type: choice
        options: [ always, on_failure, on_failure_or_cancelled, never ]
      debug-with-ssh-only-for-actor:
        description: "Limit access to the SSH session to the GitHub user that triggered the job."
        default: true
        type: boolean
      debug-with-ssh-only-jobs-matching:
        description: "Only start an SSH session for jobs matching this regex pattern:"
        default: ".*"
        type: string

defaults:
  run:
    shell: bash

jobs:
  setup-haxe-targets-action-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:  # https://github.com/actions/runner-images#available-images
        - ubuntu-latest
        - macos-15-intel
        - macos-latest # ARM
        - windows-latest

    steps:
    - name: Show environment variables
      run: env | sort

    - name: Git Checkout
      uses: actions/checkout@v7  # https://github.com/actions/checkout

    - name: "Install: Haxe compiler targets (default versions)"
      uses: ./.github/actions/setup-haxe-targets
      with:
        haxe-reusable-workflows-repo:    ${{ github.repository }}
        haxe-reusable-workflows-version: ${{ github.ref }}

        setup-cs:     true
        setup-flash:  true
        setup-hl:     true
        setup-java:   true
        setup-lua:    true
        setup-node:   true
        setup-php:    true
        setup-python: true

    - name: "Install: Haxe compiler targets (specific versions)"
      uses: ./.github/actions/setup-haxe-targets
      with:
        haxe-reusable-workflows-repo:    ${{ github.repository }}
        haxe-reusable-workflows-version: ${{ github.ref }}

        setup-cs:     '6.10'
        setup-flash:  false
        setup-hl:     false
        setup-java:   17
        setup-lua:    5.2.4
        setup-node:   20
        setup-php:    8.2
        setup-python: 3.11


    ##################################################
    # Setup SSH debug session
    ##################################################
    - name: "SSH session for debugging: check"
      id: DEBUG_SSH_SESSSION_CHECK
      if: always()
      run: |
        set -eu
        job_filter_pattern="${{ inputs.debug-with-ssh-only-jobs-matching }}"
        echo "job_filter: $job_filter_pattern"

        job_info=$(echo "$GITHUB_JOB ${{ toJSON(matrix) }}" | tr -d '\n')
        echo "job_info: $job_info"

        when="${{ inputs.debug-with-ssh }}"

        if [[ $when == "always" ]] || { [[ "$job_info" =~ .*$job_filter_pattern.* ]] && case "${{ job.status }}" in
          success)   [[ $when == "always" ]] ;;
          cancelled) [[ $when == "on_failure_or_cancelled" ]] ;;
          failure)   [[ $when == "on_failure"* ]] ;;
        esac }; then
          echo "start_ssh_session=true" | tee -a "$GITHUB_OUTPUT"
        fi

    - name: "SSH session for debugging: start"
      uses: mxschmitt/action-tmate@v3  # https://github.com/mxschmitt/action-tmate
      if: always() && steps.DEBUG_SSH_SESSSION_CHECK.outputs.start_ssh_session
      with:
        limit-access-to-actor: ${{ inputs.debug-with-ssh-only-for-actor }}
