# SPDX-FileCopyrightText: © Vegard IT GmbH (https://vegardit.com) and contributors
# SPDX-FileContributor: Sebastian Thomschke, Vegard IT GmbH
# SPDX-License-Identifier: Apache-2.0
#
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Test "test-with-haxe" Action

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - '**/*.adoc'
    - '**/*.md'
    - '.github/*.yml'
    - '.github/workflows/test-with-haxe.yml'
    - '.github/workflows/build.action-setup-haxe-targets.yml'
    - '.github/workflows/build.workflow-test-with-haxe.yml'
  pull_request:
  workflow_dispatch:
    # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
    inputs:
      debug-with-ssh:
        description: "Start an SSH session for debugging purposes after tests ran:"
        default: never
        type: choice
        options: [ always, on_failure, on_failure_or_cancelled, never ]
      debug-with-ssh-only-for-actor:
        description: "Limit access to the SSH session to the GitHub user that triggered the job."
        default: true
        type: boolean
      debug-with-ssh-only-jobs-matching:
        description: "Only start an SSH session for jobs matching this regex pattern:"
        default: ".*"
        type: string

jobs:
  test-with-haxe-action-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
        - ubuntu-latest
        - macos-latest
        - windows-latest
        haxe:
        - nightly
        - 4.3.2
        - 4.2.5
        - 3.4.7

    steps:
    - name: Show environment variables
      run: env | sort

    - name: Git Checkout
      uses: actions/checkout@v4 #https://github.com/actions/checkout

    - name: "Test with Haxe"
      uses: ./.github/actions/test-with-haxe
      with:
        haxe-reusable-workflows-repo:    ${{ github.repository }}
        haxe-reusable-workflows-version: ${{ github.ref }}

        haxe-version: ${{ matrix.haxe }}
        haxe-libs: |
          haxe-doctest          # install latest version from lib.haxe.org
          haxe-concurrent@4.1.0 # install fixed version from lib.haxe.org
          haxe-files@git:https://github.com/vegardit/haxe-files # install version from default git branch
          haxe-strings@git:https://github.com/vegardit/haxe-strings#v7.0.2 # install version from specific git tag

        test-cpp: true
        test-cs: true
        test-eval: true
        test-flash: |
          haxe-args: "tests-flash.hxml"
          enabled: ${{ !startsWith(matrix.os, 'macos') }} # FlashPlayer hangs on MacOS
          retries: 10
          timeout-minutes: 1
          allow-failure: true
        test-hl: ${{ matrix.haxe != '3.4.7' }}
        test-java: true
        test-jvm: true
        test-lua: true
        test-neko: true
        test-node: tests.hxml
        test-php: true
        test-python: true

        debug-with-ssh: ${{ inputs.debug-with-ssh || 'never' }}
        debug-with-ssh-only-for-actor: ${{ inputs.debug-with-ssh-only-for-actor || false }}
        debug-with-ssh-only-jobs-matching: ${{ inputs.debug-with-ssh-only-jobs-matching }}

    - name: "Test with Haxe (continue-on-error)"
      uses: ./.github/actions/test-with-haxe
      if: runner.os != 'Windows' # TODO https://github.com/krdlab/setup-haxe/pull/29
      with:
        haxe-reusable-workflows-repo:    ${{ github.repository }}
        haxe-reusable-workflows-version: ${{ github.ref }}

        haxe-version: ${{ matrix.haxe }}
        haxe-args: -cp test -main MainWithError
        retries: 1

        test-cpp: |
          allow-failure: true
          enabled: true
        test-cs: |
          allow-failure: true
          enabled: true
        test-eval: |
          allow-failure: true
          enabled: true
        test-flash: |
          haxe-args: "tests-flash.hxml"
          enabled: ${{ !startsWith(matrix.os, 'macos') }} # FlashPlayer hangs on MacOS
          timeout-minutes: 1
          allow-failure: true
        test-hl: |
          allow-failure: true
          enabled: true
        test-java: |
          allow-failure: true
          enabled: true
        test-jvm: |
          allow-failure: true
          enabled: true
        test-lua: |
          allow-failure: true
          enabled: true
        test-neko: |
          allow-failure: true
          enabled: true
        test-node: |
          allow-failure: true
          enabled: true
        test-php: |
          allow-failure: true
          enabled: true
        test-python: |
          allow-failure: true
          enabled: true
