# SPDX-FileCopyrightText: © Vegard IT GmbH (https://vegardit.com) and contributors
# SPDX-FileContributor: Sebastian Thomschke, Vegard IT GmbH
# SPDX-License-Identifier: Apache-2.0
#
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Test Reusable Workflow

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - '**/*.adoc'
    - '**/*.md'
    - '.github/*.yml'
    - '.github/actions/test-with-haxe/action.yml'
    - '.github/workflows/*composite*.yml'
  pull_request:
  workflow_dispatch:
    # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
    inputs:
      debug-with-ssh:
        description: "Start an SSH session for debugging purposes after tests ran:"
        default: never
        type: choice
        options: [ always, on_failure, on_failure_or_cancelled, never ]
      debug-with-ssh-only-for-actor:
        description: "Limit access to the SSH session to the GitHub user that triggered the job."
        default: true
        type: boolean
      debug-with-ssh-only-jobs-matching:
        description: "Only start an SSH session for jobs matching this regex pattern:"
        default: ".*"
        type: string

jobs:
  test-reusable-workflow:
    uses: ./.github/workflows/reusable.test-with-haxe.yml
    strategy:
      fail-fast: false
      matrix:
        os: 
        - ubuntu-latest
        - macos-latest
        - windows-latest
        haxe:
        - latest
        - 4.2.5
        - 3.4.7
    with:
      runner-os: ${{ matrix.os }}
      haxe-version: ${{ matrix.haxe }}
      haxe-libs: hx3compat hscript@2.5.0
      test-cpp: true
      test-cs: true
      test-eval: true
      test-flash: ${{ !startsWith(matrix.os, 'macos') && 'tests-flash.hxml' || false }} # FlashPlayer hangs on MacOS
      test-hl: ${{ matrix.haxe != '3.4.7' }}
      test-java: true
      test-jvm: true
      test-lua: true
      test-neko: true
      test-node: true
      test-php: true
      test-python: true

      before-tests: |
        echo "Preparing tests..."

      after-tests: |
        case "$GITHUB_JOB_STATUS" in
          success)   echo "Job success" ;;
          failure)   echo "Job failure" ;;
          cancelled) echo "Job cancelled." ;;
          *)         echo "ERROR: Unexpected job status $GITHUB_JOB_STATUS"; exit 1 ;;
        esac

      debug-with-ssh: ${{ inputs.debug-with-ssh || 'never' }}
      debug-with-ssh-only-for-actor: ${{ inputs.debug-with-ssh-only-for-actor || false }}
      debug-with-ssh-only-jobs-matching: ${{ inputs.debug-with-ssh-only-for-actor }}
