# SPDX-FileCopyrightText: © Vegard IT GmbH (https://vegardit.com) and contributors
# SPDX-FileContributor: Sebastian Thomschke, Vegard IT GmbH
# SPDX-License-Identifier: Apache-2.0
#
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Test Composite Action

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - '**/*.adoc'
    - '**/*.md'
    - '.github/*.yml'
  pull_request:
  workflow_dispatch:
    # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

jobs:
  test-composite-action:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
        - ubuntu-latest
        - macos-latest
        - windows-latest
        haxe:
        - latest
        - 4.2.5
        - 3.4.7

    steps:
    - name: Show environment variables
      run: env | sort

    - name: Git Checkout
      uses: actions/checkout@v3 #https://github.com/actions/checkout

    - name: "Test with Haxe"
      uses: ./.github/actions/test-with-haxe
      with:
        haxe-version: ${{ matrix.haxe }}
        haxe-libs: hx3compat hscript@2.5.0
        test-cpp: true
        test-cs: true
        test-eval: true
        test-hl: ${{ matrix.haxe != '3.4.7' }}
        test-java: true
        test-jvm: true
        test-lua: true
        test-neko: true
        test-node: true
        test-php: true
        test-python: true
