# SPDX-FileCopyrightText: © Vegard IT GmbH (https://vegardit.com) and contributors
# SPDX-FileContributor: Sebastian Thomschke, Vegard IT GmbH
# SPDX-License-Identifier: Apache-2.0
#
# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: Setup Haxe Lua Target
description: Installs and configures the Haxe compiler target Lua

inputs:
  python-version: 
    default: "3.11"
    description: "Python version"

runs:
  using: "composite"
  steps:
    - name: "Setup Python: Install Python"
      uses: actions/setup-python@v5 # https://github.com/actions/setup-python
      with:
        python-version: ${{inputs.python-version }}

    - name: "Setup Python: Fix Windows installation bug"
      if: runner.os == 'Windows'
      shell: cmd
      run: # workaround for https://github.com/actions/setup-python/issues/123
        if not exist "%pythonLocation%\python.exe" (
          mklink "%pythonLocation%\python3.exe" "%pythonLocation%\python.exe"
        )

    - name: "Setup Python: Verify PATH"
      shell: bash
      run: python --version
